// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace OrderApi.SignalR.Services.Data
{
    public partial class Users
    {
        public Users()
        {
            Connections = new HashSet<Connections>();
            Messages = new List<Messages>();
        }
        [Key]
        public string UserId { get; set; }

        public virtual ICollection<Connections> Connections { get; set; }
        public virtual ICollection<Messages> Messages { get; set; }
    }
}